version = 1

[update]
# Automatically rebases/updates the PR when the base branch changes
always_update = true

[merge]
# Ensures the final merge uses the rebase method
method = "rebase"
automerge_label = "automerge"
