savePrefix: ''
blockExoticSubdeps: true
minimumReleaseAge: 1440 # In minutes -- 1440 minutes = 1 day
minimumReleaseAgeExclude:
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  - 'semver@5.7.2'
  - 'semver@7.8.0'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
overrides:
  "semver": "7.8.0"
  "msgpackr": "2.0.1"