savePrefix: ''
blockExoticSubdeps: true
minimumReleaseAge: 1440 # In minutes -- 1440 minutes = 1 day
minimumReleaseAgeExclude:
  - webpack@5.107.0
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  - 'semver@5.7.2'
  - 'semver@7.8.0'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
overrides:
  "semver": "7.8.0"
  "msgpackr": "2.0.1"
  '@parcel/reporter-dev-server@>=1.6.1 <=2.16.3': ^2.16.4
  cookie@<0.7.0: ^0.7.0
  file-type@>=13.0.0 <21.3.1: ^21.3.1
  lodash@<=4.17.23: ^4.17.24
  lodash@>=4.0.0 <=4.17.23: ^4.17.24
  on-headers@<1.1.0: ^1.1.0
  path-to-regexp@<0.1.13: ^0.1.13
  serialize-javascript@<7.0.5: ^7.0.5
  serialize-javascript@<=7.0.2: ^7.0.3
  webpack@>=5.49.0 <5.104.0: ^5.104.0
  webpack@>=5.49.0 <=5.104.0: ^5.107.0
  ws@>=8.0.0 <8.21.0: 8.21.1
  immutable@<4.3.9: 4.3.9
  tmp@<0.2.6: 0.2.7
  shell-quote@<=1.8.4: 1.10.0
  axios@<1.18.0: 1.19.0
  brace-expansion@>=1.0.0 <1.1.17: 1.1.18
  fast-uri@<3.1.4: 3.1.4
  form-data@>=4.0.0 <4.0.6: 4.0.6
  js-yaml@>=3.0.0 <3.15.0: 3.15.0
  multer@>=2.0.0 <2.2.0: 2.2.0
  postcss@<8.5.18: 8.5.25
  sharp@<0.35.0: 0.35.3
  svgo@>=2.0.0 <2.8.3: 2.8.3
  '@babel/core@<7.29.1': 7.29.7
  body-parser@>=1.0.0 <1.20.6: 1.20.6
  body-parser@>=2.0.0 <2.3.0: 2.3.0
  joi@<17.13.4: 17.13.4
  sanitize-html@<2.17.5: 2.17.6
  uuid@<11.1.1: 11.1.1
